server:
  port: 8080
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: reggie_take_out
  cache:
    redis:
      time-to-live: 1800000
  redis:
      host: 106.53.147.3
      port: 6379
      database: 0
      password: 823113
  shardingsphere:
    datasource:
      names:
        master, slave
      # 主数据源
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://106.53.147.3:3306/reggie?characterEncoding=utf-8
        username: root
        password: 823113
      # 从数据源
      slave:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/reggie?characterEncoding=utf-8
        username: root
        password: 823113
    masterslave:
      # 读写分离配置
      load-balance-algorithm-type: round_robin #轮询
      # 最终的数据源名称
      name: dataSource
      # 主库数据源名称
      master-data-source-name: master
      # 从库数据源名称列表，多个逗号分隔
      slave-data-source-names: slave
    props:
      sql:
        show: true #开启SQL显示，默认false
  rabbitmq:
    host: 106.53.147.3
    port: 5672
    username: admin
    password: 823113
    publisher-confirm-type: correlated
    publisher-returns: true
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
reggie:
  path: /image/

ali-pay:
  #接下来两个用来标识用户
  #商户id
  pid: 2088621991142357
  #应用appid(和商户id绑定过)
  app-id: 2021000121650414
  #接下来三个用来确保SSL
  #商户私钥
  merchant-private-key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCSGTjTTX3pLjZpNpPgfXZtekAZYQWjm6HV1aWuRqarr1oPhrDiFAUSYueoCKkhxEySh3yC7CfYMcZA/Ve108cmUxX0HNaMs5++QYtADTJqcvVqwLz0PvRf2eeMoFtpaeIXb3vk25MgBMb1Z9hUsYNFpfVmMkAoAJ1YjGdcjcsn3EwIlJLo7cYEYxQ7PVu2edo9hT8xdtN5dhP7eHtEmLS/WiwtigsR1OwahsvDigXwAj+KNV+4RoBmoT4wJX5s3XP2YFhhx78QMbOta10fmZ33xN06ToOv7Zce4BKS8HWPPYnNvd2tUuJHYBZpVEQgpXGbbQDBpemEZkQOrFH5nBqtAgMBAAECggEAbxX8bjYiwbVgq9lS0UO0U4O7z1BFQGRqxjOfuYaA3lQDT4DjZ9M/E/7eE5caOtGOQ2//TXEQzsLx8qJvGZMAfvR34dg3jl5Z3QjrP3WJWwUz88q/IZvopiUCeZvIRbu7rIQZGSeXk6XuPdSK2cLrhH6uu9kDjScCfLytLuOlkBU7ZRRBBIlOa77d3+/858vpMu5RAUU09rCG5mR/Di+9YhoGR/sjtN3uPi986n+HZY0ye3/KM/UL2LlD2D9SKE9TX85J2uznhx6bEhCoR8nbI4VMHU/YyDKEE/ONaYLx4hyeJKN4Jge3HE+XOAOeUxYlKte4eoUCq6JDZ6Zw0+BlQQKBgQDPuzftN2PgvMSVVUxCxNh1IWuB0yGDStnc9qAARkcsFiNLuMMXZ10ogZNSJ7EzZBLGicMmryY9zPGYI2REySndpX1BgqVFWCYtaZd8EpHG4tmdyC9BN9QGKsw2UJJKMKZa/fGc/KNmhcV0UTdRew6i/V58QaSjxpd+w2BA2HLPnQKBgQC0C8+ZtDf8V1PkkVHgO83+ELlJOZ7dGGoOSQGSaUJIgFLws1KJHe6UmFn0ZFCdtVrefJ65Y4wn9YqoHMcB+6/JglX/nmpW+DxWtxdI4T/SiICT1YpjfJvjtCUda9cHbZ6ykDBi2zFXAOCZ8sfbHoUt85gqnY7GZ0Y21eDaUT7yUQKBgCMdHHkGseVdQ0WS448twwEZoxiQ3ctZrbYCIk2pk4JKQ7EbDC86k66zKHnsp7FuKxZQVyKE3Mv5hqUW5m4SKveCb8fRE6rDGcD3ZlncsbOSyQI4wnQdwcNBHL/ZosDTtGsRHfRRaDV+S0A8MkOdr32xonUSi4f7m8Qbtnt/mvipAoGBAK5UQU6yEQNkCvblPkG/plS6HK2p/QhW+1mZlswM3wEUPzqQZvoc4UU/vtnDx8rsLm/+ejFHEg4e0YK1WnuxFyQl7t7ypERRVxsfbIxEjWdshBKgUL7DiK2RX9587Fdk7KQ4uKD/W2bCkrZ9PMYNZyZ3Fn8sz3GLzZCKxoyc3jYBAoGBAM2tVtUDvxMX3w7NEzBL4WYJsRqkwJKElJjFNwR94fmzOuwMoDQcn9kuwFKg0Ku8C5n6fOCiEKtXBR9G3jLZ1wG87nVP/+CAo6PlzZqZ/3ywQ6WR6z9uST1IqYzLNPLFX9mKk90/quQ/XOVJwvXTUZkZPcMiDKOfC7TyUqMXEIGj
  #支付宝公钥
  ali-pay-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAl9U80YWpCf2AETFT1XUzjm1yjxMJNxTJcHhhhfTKXCUlzdEsclyICCG2vyDyP4Fk6kLIrS+Oy1WCrauMycUsD9p0I19rW7Nq7D8IPVcvzWRnTL8qI/l8mPDhASxh4FXCKqdkJUJm6LaxHc+BwF4Rtkz/Z1lixjTqahK5ldNW85fTe+DSEbQTAU/UV8qR0YBKaU9qFCFgNvmwhG5D4E1sft3ae8AnNf2HHI2RWTYwiCFMk78HJIm0sJyfsBRSBYBLnUekJ1wHyC3sF0ogb7ZYsnPypkQ//ViXfF3NILZ0nFLxiFklRNZ/bmEQGvx1pqbAErya8duiD08t3Fdu38vgPwIDAQAB
  #  content-key:
  #接下来三个是相关地址
  #支付宝网关
  gateway-url: https://openapi.alipaydev.com/gateway.do
  #接收结果通知地址
  notify-url:  https://5e86-110-53-234-151.jp.ngrok.io/order/pay
  #页面跳转同步通知页面路径
  return-url: http://localhost:8080/front/page/pay-success.html